# Site settings
title: Lamar Lyons blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://Engineermar.github.io"
github_username:  Engineermar

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
